const VALIDATION_ERROR = 400
const FILE_NOT_FOUND = 404
const AUTHENTICATION_ERROR =403
const SERVER_ERROR = 500 
module.exports = {VALIDATION_ERROR,FILE_NOT_FOUND, AUTHENTICATION_ERROR, SERVER_ERROR}